### ISSUE TITLE
Issue with Insta posting.

### ISSUE THREAD

**Issue by ghuser9822** [Xacnio/tweetcapture#11]
Seems like there is some issue with insta login.

It was working fine. But now throwing issue... 

Might be some issue with the headers being used. https://stackoverflow.com/a/35010312

How to resolve this and how much frequency do you suggest per hour /day of login through this?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/InstaTweetFW/finInsta.py", line 129, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/InstaTweetFW/finInsta.py", line 73, in main
    upload_post_photo(jpg_name,captions)
  File "/root/InstaTweetFW/finInsta.py", line 34, in upload_post_photo
    cl.login(IG_USERNAME, IG_PASSWORD)
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 447, in private_request
    raise e
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: The username you entered doesn't appear to belong to an account. Please check your username and try again.
```

**Comment by Xacnio** [comment]
It's not about tweetcapture package. Go to this repo: https://github.com/adw0rd/instagrapi

**Comment by ghuser9822** [comment]
thank you for redirecting :)
