### ISSUE TITLE
Not working on Ubuntu without GUI.

### ISSUE THREAD

**Issue by ghuser9822** [Xacnio/tweetcapture#9]
It is working perfectly on Windows.
But when i tried it on cli based ubuntu system without any GUI (Basically a server) it is not working.

Traceback (most recent call last):
  File "/root/InstaTweetCC/instatweet.py", line 44, in main
    path = await tweet.screenshot(tweet_url, "testig.png", mode=0, night_mode=2)
  File "/usr/local/lib/python3.10/dist-packages/tweetcapture/screenshot.py", line 43, in screenshot
    driver = await get_driver(self.chrome_opts, self.driver_path)
  File "/usr/local/lib/python3.10/dist-packages/tweetcapture/utils/webdriver.py", line 25, in get_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_respo                 nse
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming                  that Chrome has crashed.)
Stacktrace:
#0 0x559f2b3de693 <unknown>
#1 0x559f2b1d7b0a <unknown>
#2 0x559f2b1fcef2 <unknown>
#3 0x559f2b1f81f4 <unknown>
#4 0x559f2b233953 <unknown>
#5 0x559f2b22d743 <unknown>
#6 0x559f2b203533 <unknown>
#7 0x559f2b204715 <unknown>
#8 0x559f2b42e7bd <unknown>
#9 0x559f2b431bf9 <unknown>
#10 0x559f2b413f2e <unknown>
#11 0x559f2b4329b3 <unknown>
#12 0x559f2b407e4f <unknown>
#13 0x559f2b451ea8 <unknown>
#14 0x559f2b452052 <unknown>
#15 0x559f2b46c71f <unknown>
#16 0x7f2b66e87b43 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/InstaTweetCC/instatweet.py", line 124, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/InstaTweetCC/instatweet.py", line 46, in main
    traceback.print_exc()
NameError: name 'traceback' is not defined

**Comment by Xacnio** [comment]
Did you install chrome or chromium?

Install with Snap:

`root@ubuntu: 
snap refresh chromium --channel=latest/candidate`

If you get an error about version, you can check other versions.
`snap info chromium`

**Comment by ghuser9822** [comment]
Both Chromium and Chrome were installed, and I tried your idea.still
I'm still having the same problem.

Because there is no GUI on a linux cli-based system, UI drivers and programmes may not support rendering or services.

There is a technique to run Google Chrome on a cli-based system. simply executing code with the —no-sandbox flag.

google-chrome —no-sandbox

But I'm not sure how to execute this through the chrome-driver, which is utilised in util.py.

**Comment by Xacnio** [comment]
This is already able to run without GUI. I'm using with only cli - SSH on my Ubuntu server.

Could you remove google chrome? Only chromium is installed on my server and it's working.

Or, maybe you need to this, try the arguments:
```
tweet = TweetCapture()
tweet.add_chrome_argument('--no-sandbox')
tweet.add_chrome_argument('--disable-gpu')
```

**Comment by ghuser9822** [comment]
Issue resolved with --no-sandbox and --disable-gpu.

thank you buddy.
